databases:
  - name: netflixdb
    plan: free
    databaseName: netflixdb
    user: netflixwebapp

services:
  - type: web
    plan: free
    name: NetflixWebApp
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn NetflixWebApp.wsgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: 'postgresql://netflixdatadatabase_user:kYlkW32ZvnCEzuru5xWKM4HZzuApB4JQ@dpg-d868ud8jo89c7386eg0g-a.ohio-postgres.render.com/netflixdatadatabase'
        fromDatabase:
          name: netflixdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4