# Generated by Django 6.0.4 on 2026-04-16 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('primary_device', models.CharField(max_length=100)),
                ('devices_used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(max_length=100)),
                ('avg_watch_time_mins', models.IntegerField()),
                ('watch_sessions_per_week', models.IntegerField()),
                ('binge_watch_sessions', models.IntegerField()),
                ('completion_rate', models.IntegerField()),
                ('rating_given', models.FloatField()),
                ('content_interactions', models.IntegerField()),
                ('recommendation_click_rate', models.IntegerField()),
                ('days_since_last_login', models.IntegerField()),
                ('churned', models.BooleanField(default=False)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_age_months', models.IntegerField()),
                ('subscription_type', models.CharField(choices=[('Standard', 'Standard'), ('Basic', 'Basic'), ('Premium', 'Premium')], max_length=100)),
                ('monthly_fee', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
                ('viewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.viewer')),
            ],
        ),
    ]
