# Generated by Django 6.0.4 on 2026-04-20 22:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_age_months', models.IntegerField()),
                ('subscription_type', models.CharField(choices=[('Standard', 'Standard'), ('Basic', 'Basic'), ('Premium', 'Premium')], max_length=100)),
                ('monthly_fee', models.FloatField(choices=[(7.99, 7.99), (12.99, 12.99), (15.99, 15.99)])),
                ('payment_method', models.CharField(choices=[('Paypal', 'Paypal'), ('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada'), ('Brazil', 'Brazil'), ('France', 'France'), ('Australia', 'Australia'), ('UK', 'UK'), ('Japan', 'Japan'), ('Germany', 'Germany')], max_length=100)),
                ('primary_device', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Smart TV', 'Smart TV')], max_length=100)),
                ('devices_used', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Documentary', 'Documentary'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller')], max_length=100)),
                ('avg_watch_time_mins', models.IntegerField()),
                ('watch_sessions_per_week', models.IntegerField()),
                ('binge_watch_sessions', models.IntegerField()),
                ('completion_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating_given', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('content_interactions', models.IntegerField()),
                ('recommendation_click_rate', models.IntegerField()),
                ('days_since_last_login', models.IntegerField()),
                ('churned', models.BooleanField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viewer'),
        ),
    ]
