# Generated by Django 6.0.4 on 2026-04-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='monthly_fee',
            field=models.FloatField(choices=[(7.99, 7.99), (12.99, 12.99), (15.99, 15.99)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card')], max_length=100),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='favorite_genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Documentary', 'Documentary'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller')], max_length=100),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('Canada', 'Canada'), ('Brazil', 'Brazil'), ('France', 'France'), ('Australia', 'Australia'), ('UK', 'UK'), ('Japan', 'Japan'), ('Germany', 'Germany')], max_length=100),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='primary_device',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Smart TV', 'Smart TV')], max_length=100),
        ),
    ]
