# Generated by Django 6.0.4 on 2026-04-29 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_behavior_id_alter_behavior_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='rating_given',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
