# Generated by Django 6.0.4 on 2026-05-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_movie_overview_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
